### ISSUE TITLE
Long url lenght fails

### ISSUE THREAD

**Issue by Seraf** [hiddentao/google-tts#9]
Hello,

When a long text is sent, google seems to abort the connection.
It should be great to detect a long string, split it, send these to google and play mp3 returned one after one.
Will try to work on a patch but can't promise anything as JS isn't a well known language for me.

Example (in french, sorry, this is the tv grid of the day) : 
Sur FRANCE 2 a 20 heure 45 il y a : Drôle de famille !. Sur FRANCE 3 a 20 heure 45 il y a : Des racines et des ailes. Sur M6 a 20 heure 50 il y a : Pékin express, le coffre maudit. Sur NRJ 12 a 20 heure 50 il y a : Les grandes histoires. Sur NT1 a 20 heure 45 il y a : Soeur Thérèse.com. Sur TF1 a 20 heure 50 il y a : Grey's Anatomy. Sur TF1 a 21 heure 35 il y a : Grey's Anatomy. Sur W9 a 20 heure 45 il y a : Météo. Sur W9 a 20 heure 50 il y a : Enquêtes criminelles : le magazine des faits divers.

Regards.

**Comment by juniorsatanas** [comment]
The limit of a file is 100 characters? how do I export to mp3 audio generated? thanks You

**Comment by hiddentao** [comment]
@juniorsatanas This library's not really built for exporting the MP3, plus I'm sure that goes against Google's terms and conditions.
